// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: v1/channel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//频道操作
type ChannelHandleType int32

const (
	ChannelHandleType_CHANNEL_UNKNOWN_HANDLE    ChannelHandleType = 0  //未知
	ChannelHandleType_CHANNEL_MODIFICATION_NAME ChannelHandleType = 1  //修改频道名称
	ChannelHandleType_CHANNEL_NO_DISTURB        ChannelHandleType = 2  //频道消息免打扰
	ChannelHandleType_CHANNEL_EDIT_PROCLAMATION ChannelHandleType = 3  //编辑频道公告
	ChannelHandleType_CHANNEL_LOOK_PROCLAMATION ChannelHandleType = 4  //查看频道公告
	ChannelHandleType_CHANNEL_QUIT              ChannelHandleType = 5  //退出频道
	ChannelHandleType_CHANNEL_FOUND             ChannelHandleType = 6  //创建频道
	ChannelHandleType_CHANNEL_DISSOLVE          ChannelHandleType = 7  //解散频道
	ChannelHandleType_CHANNEL_TOP               ChannelHandleType = 8  //置顶频道
	ChannelHandleType_CHANNEL_CHAT_RECORD       ChannelHandleType = 9  //查找频道聊天记录
	ChannelHandleType_CHANNEL_subscription      ChannelHandleType = 10 //订阅频道
)

// Enum value maps for ChannelHandleType.
var (
	ChannelHandleType_name = map[int32]string{
		0:  "CHANNEL_UNKNOWN_HANDLE",
		1:  "CHANNEL_MODIFICATION_NAME",
		2:  "CHANNEL_NO_DISTURB",
		3:  "CHANNEL_EDIT_PROCLAMATION",
		4:  "CHANNEL_LOOK_PROCLAMATION",
		5:  "CHANNEL_QUIT",
		6:  "CHANNEL_FOUND",
		7:  "CHANNEL_DISSOLVE",
		8:  "CHANNEL_TOP",
		9:  "CHANNEL_CHAT_RECORD",
		10: "CHANNEL_subscription",
	}
	ChannelHandleType_value = map[string]int32{
		"CHANNEL_UNKNOWN_HANDLE":    0,
		"CHANNEL_MODIFICATION_NAME": 1,
		"CHANNEL_NO_DISTURB":        2,
		"CHANNEL_EDIT_PROCLAMATION": 3,
		"CHANNEL_LOOK_PROCLAMATION": 4,
		"CHANNEL_QUIT":              5,
		"CHANNEL_FOUND":             6,
		"CHANNEL_DISSOLVE":          7,
		"CHANNEL_TOP":               8,
		"CHANNEL_CHAT_RECORD":       9,
		"CHANNEL_subscription":      10,
	}
)

func (x ChannelHandleType) Enum() *ChannelHandleType {
	p := new(ChannelHandleType)
	*p = x
	return p
}

func (x ChannelHandleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelHandleType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_channel_proto_enumTypes[0].Descriptor()
}

func (ChannelHandleType) Type() protoreflect.EnumType {
	return &file_v1_channel_proto_enumTypes[0]
}

func (x ChannelHandleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelHandleType.Descriptor instead.
func (ChannelHandleType) EnumDescriptor() ([]byte, []int) {
	return file_v1_channel_proto_rawDescGZIP(), []int{0}
}

type ChannelPackageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ChannelHandleType `protobuf:"varint,1,opt,name=type,proto3,enum=ChannelHandleType" json:"type,omitempty"`
	Data []byte            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ChannelPackageData) Reset() {
	*x = ChannelPackageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelPackageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPackageData) ProtoMessage() {}

func (x *ChannelPackageData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPackageData.ProtoReflect.Descriptor instead.
func (*ChannelPackageData) Descriptor() ([]byte, []int) {
	return file_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelPackageData) GetType() ChannelHandleType {
	if x != nil {
		return x.Type
	}
	return ChannelHandleType_CHANNEL_UNKNOWN_HANDLE
}

func (x *ChannelPackageData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_channel_proto protoreflect.FileDescriptor

var file_v1_channel_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x50, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0xa3, 0x02, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x48, 0x41,
	0x4e, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e,
	0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c,
	0x5f, 0x4e, 0x4f, 0x5f, 0x44, 0x49, 0x53, 0x54, 0x55, 0x52, 0x42, 0x10, 0x02, 0x12, 0x1d, 0x0a,
	0x19, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x50, 0x52,
	0x4f, 0x43, 0x4c, 0x41, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19,
	0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x4c, 0x4f, 0x4f, 0x4b, 0x5f, 0x50, 0x52, 0x4f,
	0x43, 0x4c, 0x41, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x51, 0x55, 0x49, 0x54, 0x10, 0x05, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x06,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x44, 0x49, 0x53, 0x53,
	0x4f, 0x4c, 0x56, 0x45, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x5f, 0x54, 0x4f, 0x50, 0x10, 0x08, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x09,
	0x12, 0x18, 0x0a, 0x14, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x0a, 0x42, 0x1e, 0x5a, 0x1c, 0x73, 0x75,
	0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v1_channel_proto_rawDescOnce sync.Once
	file_v1_channel_proto_rawDescData = file_v1_channel_proto_rawDesc
)

func file_v1_channel_proto_rawDescGZIP() []byte {
	file_v1_channel_proto_rawDescOnce.Do(func() {
		file_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_channel_proto_rawDescData)
	})
	return file_v1_channel_proto_rawDescData
}

var file_v1_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_channel_proto_goTypes = []interface{}{
	(ChannelHandleType)(0),     // 0: ChannelHandleType
	(*ChannelPackageData)(nil), // 1: ChannelPackageData
}
var file_v1_channel_proto_depIdxs = []int32{
	0, // 0: ChannelPackageData.type:type_name -> ChannelHandleType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_channel_proto_init() }
func file_v1_channel_proto_init() {
	if File_v1_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelPackageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_channel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_channel_proto_goTypes,
		DependencyIndexes: file_v1_channel_proto_depIdxs,
		EnumInfos:         file_v1_channel_proto_enumTypes,
		MessageInfos:      file_v1_channel_proto_msgTypes,
	}.Build()
	File_v1_channel_proto = out.File
	file_v1_channel_proto_rawDesc = nil
	file_v1_channel_proto_goTypes = nil
	file_v1_channel_proto_depIdxs = nil
}
