// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: v1/room.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//房间操作
type RoomHandleType int32

const (
	RoomHandleType_ROOM_UNKNOWN_HANDLE      RoomHandleType = 0 //未知
	RoomHandleType_ROOM_MODIFICATION_NAME   RoomHandleType = 1 //修改房间名称
	RoomHandleType_ROOM_MODIFICATION_AVATAR RoomHandleType = 2 //修改房间头像
	RoomHandleType_ROOM_SHARE               RoomHandleType = 3 //分享房间
	RoomHandleType_ROOM_REPORT              RoomHandleType = 4 //举报房间
	RoomHandleType_ROOM_CLOSURE             RoomHandleType = 5 //关闭房间
	RoomHandleType_ROOM_FOUND               RoomHandleType = 6 //创建房间
	RoomHandleType_ROOM_SEND_BARRAGE        RoomHandleType = 7 //发送弹幕
	RoomHandleType_ROOM_SUBSCRIPTION        RoomHandleType = 8 //订阅房间
)

// Enum value maps for RoomHandleType.
var (
	RoomHandleType_name = map[int32]string{
		0: "ROOM_UNKNOWN_HANDLE",
		1: "ROOM_MODIFICATION_NAME",
		2: "ROOM_MODIFICATION_AVATAR",
		3: "ROOM_SHARE",
		4: "ROOM_REPORT",
		5: "ROOM_CLOSURE",
		6: "ROOM_FOUND",
		7: "ROOM_SEND_BARRAGE",
		8: "ROOM_SUBSCRIPTION",
	}
	RoomHandleType_value = map[string]int32{
		"ROOM_UNKNOWN_HANDLE":      0,
		"ROOM_MODIFICATION_NAME":   1,
		"ROOM_MODIFICATION_AVATAR": 2,
		"ROOM_SHARE":               3,
		"ROOM_REPORT":              4,
		"ROOM_CLOSURE":             5,
		"ROOM_FOUND":               6,
		"ROOM_SEND_BARRAGE":        7,
		"ROOM_SUBSCRIPTION":        8,
	}
)

func (x RoomHandleType) Enum() *RoomHandleType {
	p := new(RoomHandleType)
	*p = x
	return p
}

func (x RoomHandleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomHandleType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_room_proto_enumTypes[0].Descriptor()
}

func (RoomHandleType) Type() protoreflect.EnumType {
	return &file_v1_room_proto_enumTypes[0]
}

func (x RoomHandleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomHandleType.Descriptor instead.
func (RoomHandleType) EnumDescriptor() ([]byte, []int) {
	return file_v1_room_proto_rawDescGZIP(), []int{0}
}

type RoomPackageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RoomHandleType `protobuf:"varint,1,opt,name=type,proto3,enum=RoomHandleType" json:"type,omitempty"`
	Data []byte         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RoomPackageData) Reset() {
	*x = RoomPackageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPackageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPackageData) ProtoMessage() {}

func (x *RoomPackageData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPackageData.ProtoReflect.Descriptor instead.
func (*RoomPackageData) Descriptor() ([]byte, []int) {
	return file_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *RoomPackageData) GetType() RoomHandleType {
	if x != nil {
		return x.Type
	}
	return RoomHandleType_ROOM_UNKNOWN_HANDLE
}

func (x *RoomPackageData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_room_proto protoreflect.FileDescriptor

var file_v1_room_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4a, 0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xd4, 0x01, 0x0a, 0x0e,
	0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17,
	0x0a, 0x13, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x48,
	0x41, 0x4e, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x4f, 0x4f, 0x4d, 0x5f,
	0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x41, 0x4d,
	0x45, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4d, 0x4f, 0x44, 0x49,
	0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x10,
	0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x45, 0x10,
	0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x55,
	0x52, 0x45, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x45, 0x4e,
	0x44, 0x5f, 0x42, 0x41, 0x52, 0x52, 0x41, 0x47, 0x45, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x52,
	0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x08, 0x42, 0x1e, 0x5a, 0x1c, 0x73, 0x75, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_room_proto_rawDescOnce sync.Once
	file_v1_room_proto_rawDescData = file_v1_room_proto_rawDesc
)

func file_v1_room_proto_rawDescGZIP() []byte {
	file_v1_room_proto_rawDescOnce.Do(func() {
		file_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_room_proto_rawDescData)
	})
	return file_v1_room_proto_rawDescData
}

var file_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_room_proto_goTypes = []interface{}{
	(RoomHandleType)(0),     // 0: RoomHandleType
	(*RoomPackageData)(nil), // 1: RoomPackageData
}
var file_v1_room_proto_depIdxs = []int32{
	0, // 0: RoomPackageData.type:type_name -> RoomHandleType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_room_proto_init() }
func file_v1_room_proto_init() {
	if File_v1_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPackageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_room_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_room_proto_goTypes,
		DependencyIndexes: file_v1_room_proto_depIdxs,
		EnumInfos:         file_v1_room_proto_enumTypes,
		MessageInfos:      file_v1_room_proto_msgTypes,
	}.Build()
	File_v1_room_proto = out.File
	file_v1_room_proto_rawDesc = nil
	file_v1_room_proto_goTypes = nil
	file_v1_room_proto_depIdxs = nil
}
