// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_ERROR_UNKNOWN       Error = 0 //未知错误
	Error_ERROR_SUCCESS       Error = 1 //成功
	Error_ERROR_FAIL          Error = 2 //失败
	Error_ERROR_PHONE_IS_USED Error = 3 //手机号已被使用
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_SUCCESS",
		2: "ERROR_FAIL",
		3: "ERROR_PHONE_IS_USED",
	}
	Error_value = map[string]int32{
		"ERROR_UNKNOWN":       0,
		"ERROR_SUCCESS":       1,
		"ERROR_FAIL":          2,
		"ERROR_PHONE_IS_USED": 3,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_v1_error_reason_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_v1_error_reason_proto protoreflect.FileDescriptor

var file_v1_error_reason_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x5c, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x5f, 0x49, 0x53, 0x5f, 0x55, 0x53,
	0x45, 0x44, 0x10, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x15, 0x5a, 0x13, 0x73, 0x75,
	0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_error_reason_proto_rawDescOnce sync.Once
	file_v1_error_reason_proto_rawDescData = file_v1_error_reason_proto_rawDesc
)

func file_v1_error_reason_proto_rawDescGZIP() []byte {
	file_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_error_reason_proto_rawDescData)
	})
	return file_v1_error_reason_proto_rawDescData
}

var file_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_error_reason_proto_goTypes = []interface{}{
	(Error)(0), // 0: Error
}
var file_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_error_reason_proto_init() }
func file_v1_error_reason_proto_init() {
	if File_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_error_reason_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_v1_error_reason_proto_enumTypes,
	}.Build()
	File_v1_error_reason_proto = out.File
	file_v1_error_reason_proto_rawDesc = nil
	file_v1_error_reason_proto_goTypes = nil
	file_v1_error_reason_proto_depIdxs = nil
}
