// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package friend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FriendClient is the client API for Friend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendClient interface {
	//修改好友状态
	UpdateFriendStatus(ctx context.Context, in *UpdateFriendStatusReq, opts ...grpc.CallOption) (*UpdateFriendStatusRsp, error)
	//修改好友备注
	UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkRsp, error)
	//列表
	ListUserFriend(ctx context.Context, in *ListUserFriendReq, opts ...grpc.CallOption) (*ListUserFriendRsp, error)
}

type friendClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendClient(cc grpc.ClientConnInterface) FriendClient {
	return &friendClient{cc}
}

func (c *friendClient) UpdateFriendStatus(ctx context.Context, in *UpdateFriendStatusReq, opts ...grpc.CallOption) (*UpdateFriendStatusRsp, error) {
	out := new(UpdateFriendStatusRsp)
	err := c.cc.Invoke(ctx, "/Friend/UpdateFriendStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkRsp, error) {
	out := new(UpdateFriendRemarkRsp)
	err := c.cc.Invoke(ctx, "/Friend/UpdateFriendRemark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendClient) ListUserFriend(ctx context.Context, in *ListUserFriendReq, opts ...grpc.CallOption) (*ListUserFriendRsp, error) {
	out := new(ListUserFriendRsp)
	err := c.cc.Invoke(ctx, "/Friend/ListUserFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServer is the server API for Friend service.
// All implementations must embed UnimplementedFriendServer
// for forward compatibility
type FriendServer interface {
	//修改好友状态
	UpdateFriendStatus(context.Context, *UpdateFriendStatusReq) (*UpdateFriendStatusRsp, error)
	//修改好友备注
	UpdateFriendRemark(context.Context, *UpdateFriendRemarkReq) (*UpdateFriendRemarkRsp, error)
	//列表
	ListUserFriend(context.Context, *ListUserFriendReq) (*ListUserFriendRsp, error)
	mustEmbedUnimplementedFriendServer()
}

// UnimplementedFriendServer must be embedded to have forward compatible implementations.
type UnimplementedFriendServer struct {
}

func (UnimplementedFriendServer) UpdateFriendStatus(context.Context, *UpdateFriendStatusReq) (*UpdateFriendStatusRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFriendStatus not implemented")
}
func (UnimplementedFriendServer) UpdateFriendRemark(context.Context, *UpdateFriendRemarkReq) (*UpdateFriendRemarkRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFriendRemark not implemented")
}
func (UnimplementedFriendServer) ListUserFriend(context.Context, *ListUserFriendReq) (*ListUserFriendRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserFriend not implemented")
}
func (UnimplementedFriendServer) mustEmbedUnimplementedFriendServer() {}

// UnsafeFriendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServer will
// result in compilation errors.
type UnsafeFriendServer interface {
	mustEmbedUnimplementedFriendServer()
}

func RegisterFriendServer(s grpc.ServiceRegistrar, srv FriendServer) {
	s.RegisterService(&Friend_ServiceDesc, srv)
}

func _Friend_UpdateFriendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).UpdateFriendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Friend/UpdateFriendStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).UpdateFriendStatus(ctx, req.(*UpdateFriendStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_UpdateFriendRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendRemarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).UpdateFriendRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Friend/UpdateFriendRemark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).UpdateFriendRemark(ctx, req.(*UpdateFriendRemarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Friend_ListUserFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServer).ListUserFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Friend/ListUserFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServer).ListUserFriend(ctx, req.(*ListUserFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Friend_ServiceDesc is the grpc.ServiceDesc for Friend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Friend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Friend",
	HandlerType: (*FriendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateFriendStatus",
			Handler:    _Friend_UpdateFriendStatus_Handler,
		},
		{
			MethodName: "UpdateFriendRemark",
			Handler:    _Friend_UpdateFriendRemark_Handler,
		},
		{
			MethodName: "ListUserFriend",
			Handler:    _Friend_ListUserFriend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/friend/friend.proto",
}
